/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

import { CHAR_WIDTH } from '~/components/dimension-utils'

/** Matches SVG export in asset-export.tsx */
const ASCII_FONT_SIZE_PX = 12
const ASCII_LINE_HEIGHT_RATIO = 1.2

export interface ReactExportVisualSettings {
  textColor: string
  backgroundColor: string
  /** Cell padding (same units as Mitos export options). */
  padding: number
}

export interface GenerateReactComponentSourceParams {
  /** PascalCase component name; invalid values fall back to AsciiArtEmbed. */
  componentName?: string
  mode: 'static' | 'animated'
  /** Single-frame ASCII (newline-separated lines). */
  text: string
  /** One string per frame when mode is animated. */
  frames?: readonly string[]
  /** Requested FPS; clamped to [10, 30] to match video export. */
  fps: number
  settings: ReactExportVisualSettings
}

function sanitizeComponentName(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, '')
  if (!cleaned || /^[0-9]/.test(cleaned)) {
    return 'AsciiArtEmbed'
  }
  return cleaned
}

function clampExportFps(fps: number): number {
  return Math.min(30, Math.max(10, fps))
}

function buildPreStyleLiteral(settings: ReactExportVisualSettings): string {
  const paddingPx = settings.padding * CHAR_WIDTH
  const lineHeightPx = ASCII_FONT_SIZE_PX * ASCII_LINE_HEIGHT_RATIO

  return [
    '{',
    `margin: 0,`,
    `color: ${JSON.stringify(settings.textColor)},`,
    `backgroundColor: ${JSON.stringify(settings.backgroundColor)},`,
    `padding: ${paddingPx},`,
    `whiteSpace: 'pre' as const,`,
    `fontFamily: ${JSON.stringify('GT America Mono, ui-monospace, monospace')},`,
    `fontSize: ${ASCII_FONT_SIZE_PX},`,
    `lineHeight: '${lineHeightPx}px',`,
    `letterSpacing: 0,`,
    '}',
  ].join(' ')
}

/**
 * Produce a self-contained .tsx source string consumers can paste into a React app.
 * Embeds ASCII as string data (static or pre-rendered frames); does not bundle Mitos runtime.
 */
export function generateReactComponentSource(
  params: GenerateReactComponentSourceParams,
): string {
  const componentName = sanitizeComponentName(params.componentName ?? 'AsciiArtEmbed')
  const styleExpr = buildPreStyleLiteral(params.settings)

  const banner = `/*
 * Generated by Mitos (https://github.com/oxidecomputer/mitos).
 * Paste into a React project with "jsx": "react-jsx" (or import React explicitly for older setups).
 * GT America Mono may require a separate font license; ui-monospace/monospace are fallbacks.
 */

`

  const propsBlock = `export interface ${componentName}Props {
  className?: string
}
`

  if (params.mode === 'static') {
    const asciiLiteral = JSON.stringify(params.text)

    return (
      banner +
      propsBlock +
      `const ASCII_ART = ${asciiLiteral}

export function ${componentName}({ className }: ${componentName}Props) {
  return (
    <pre className={className} style={${styleExpr}}>
      {ASCII_ART}
    </pre>
  )
}
`
    )
  }

  const frames = params.frames ?? []
  if (frames.length === 0) {
    throw new Error('Animated React export requires at least one frame')
  }

  const fps = clampExportFps(params.fps)
  const frameMs = Math.round(1000 / fps)
  const framesLiteral = JSON.stringify(frames)

  return (
    banner +
    `import { useEffect, useState } from 'react'

` +
    propsBlock +
    `const FRAMES = ${framesLiteral} as const

const FRAME_INTERVAL_MS = ${frameMs}

export function ${componentName}({ className }: ${componentName}Props) {
  const [frameIndex, setFrameIndex] = useState(0)

  useEffect(() => {
    const id = window.setInterval(() => {
      setFrameIndex((i) => (i + 1) % FRAMES.length)
    }, FRAME_INTERVAL_MS)
    return () => window.clearInterval(id)
  }, [])

  return (
    <pre className={className} style={${styleExpr}}>
      {FRAMES[frameIndex]}
    </pre>
  )
}
`
  )
}
